"""create core schema

Revision ID: 08f9bccd529b
Revises: 
Create Date: 2026-10-09 10:58:52.008991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08f9bccd529b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_table('print_categories',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_print_categories_active_name', 'print_categories', ['name'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'STAFF')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workflow_stages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_initial', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence > 0', name='ck_workflow_stages_sequence_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['print_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'sequence', deferrable=True, initially='IMMEDIATE', name='uq_workflow_stages_category_sequence'),
    sa.UniqueConstraint('id', 'category_id', name='uq_workflow_stages_id_category')
    )
    op.create_index(op.f('ix_workflow_stages_category_id'), 'workflow_stages', ['category_id'], unique=False)
    op.create_index('uq_workflow_stages_active_name_per_category', 'workflow_stages', ['category_id', 'name'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('uq_workflow_stages_one_active_final', 'workflow_stages', ['category_id'], unique=True, postgresql_where=sa.text('is_active = true AND is_final = true'))
    op.create_index('uq_workflow_stages_one_active_initial', 'workflow_stages', ['category_id'], unique=True, postgresql_where=sa.text('is_active = true AND is_initial = true'))
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('lead_status', sa.String(length=32), nullable=False),
    sa.Column('current_stage_id', sa.Uuid(), nullable=True),
    sa.Column('quoted_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lead_status IN ('NEW_INQUIRY', 'QUOTATION_PREPARED', 'AWAITING_CONFIRMATION', 'CONFIRMED', 'LOST', 'CANCELLED')", name='ck_jobs_lead_status'),
    sa.CheckConstraint('advance_amount >= 0', name='ck_jobs_advance_amount_nonnegative'),
    sa.CheckConstraint('final_amount IS NULL OR final_amount >= 0', name='ck_jobs_final_amount_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_jobs_quantity_positive'),
    sa.CheckConstraint('quoted_amount IS NULL OR quoted_amount >= 0', name='ck_jobs_quoted_amount_nonnegative'),
    sa.ForeignKeyConstraint(['category_id'], ['print_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_stage_id', 'category_id'], ['workflow_stages.id', 'workflow_stages.category_id'], name='fk_jobs_current_stage_same_category', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_number')
    )
    op.create_index('ix_jobs_category_id', 'jobs', ['category_id'], unique=False)
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_current_stage_id', 'jobs', ['current_stage_id'], unique=False)
    op.create_index('ix_jobs_customer_id', 'jobs', ['customer_id'], unique=False)
    op.create_index('ix_jobs_due_date', 'jobs', ['due_date'], unique=False)
    op.create_index('ix_jobs_lead_status', 'jobs', ['lead_status'], unique=False)
    op.create_index('ix_jobs_next_follow_up_at', 'jobs', ['next_follow_up_at'], unique=False)
    op.create_table('job_status_history',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage_id', sa.Uuid(), nullable=True),
    sa.Column('to_stage_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_stage_id'], ['workflow_stages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_stage_id'], ['workflow_stages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_status_history_from_stage_id'), 'job_status_history', ['from_stage_id'], unique=False)
    op.create_index('ix_job_status_history_job_id_created_at', 'job_status_history', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_status_history_to_stage_id'), 'job_status_history', ['to_stage_id'], unique=False)
    op.create_index(op.f('ix_job_status_history_updated_by_user_id'), 'job_status_history', ['updated_by_user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('reference_number', sa.String(length=160), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_job_id_paid_at', 'payments', ['job_id', 'paid_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_job_id_paid_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_job_status_history_updated_by_user_id'), table_name='job_status_history')
    op.drop_index(op.f('ix_job_status_history_to_stage_id'), table_name='job_status_history')
    op.drop_index('ix_job_status_history_job_id_created_at', table_name='job_status_history')
    op.drop_index(op.f('ix_job_status_history_from_stage_id'), table_name='job_status_history')
    op.drop_table('job_status_history')
    op.drop_index('ix_jobs_next_follow_up_at', table_name='jobs')
    op.drop_index('ix_jobs_lead_status', table_name='jobs')
    op.drop_index('ix_jobs_due_date', table_name='jobs')
    op.drop_index('ix_jobs_customer_id', table_name='jobs')
    op.drop_index('ix_jobs_current_stage_id', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_index('ix_jobs_category_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('uq_workflow_stages_one_active_initial', table_name='workflow_stages', postgresql_where=sa.text('is_active = true AND is_initial = true'))
    op.drop_index('uq_workflow_stages_one_active_final', table_name='workflow_stages', postgresql_where=sa.text('is_active = true AND is_final = true'))
    op.drop_index('uq_workflow_stages_active_name_per_category', table_name='workflow_stages', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_workflow_stages_category_id'), table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_table('users')
    op.drop_index('uq_print_categories_active_name', table_name='print_categories', postgresql_where=sa.text('is_active = true'))
    op.drop_table('print_categories')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
